# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c83e78622adbd5d541eba9d1fd4c1d8ae7eb145a8622852b865e8336face10e0710da75f5b0279fd7a556e24b4096955e4bbbfefb5c9a0aed653b913be6953a

test:
  secret_key_base: 411c37d882e3d541fffda84af3cc2b3b4cd201da5c1681332db719e414339bbc927411f507d285b33f977d3980af901fe5b6be82134c0dab168e268cfddab19e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
